version: '3.8'
services:
  mysql:
    image: mysql:8.2
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: saju8ja
      MYSQL_USER: test1234
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
